"""Market maker configuration — all thresholds and parameters."""

# Assets: binance symbol → kalshi series ticker
MM_ASSETS = {
    "BTC/USDT": "KXBTC15M",
    "ETH/USDT": "KXETH15M",
    "SOL/USDT": "KXSOL15M",
    "XRP/USDT": "KXXRP15M",
}

# Spread (in cents)
SPREAD_MIN_CENTS = 2
SPREAD_DEFAULT_CENTS = 3
SPREAD_MAX_CENTS = 4

# VPIN thresholds (calibrated for crypto — spot flow is inherently directional)
VPIN_SAFE = 0.6
VPIN_CAUTION = 0.8
VPIN_SPOT_WEIGHT = 0.7
VPIN_KALSHI_WEIGHT = 0.3
VPIN_WINDOW_SECONDS = 120

# Timing (seconds unless noted)
POLL_INTERVAL = 3
QUOTE_WINDOW_MIN_MINUTES = 5
QUOTE_WINDOW_MAX_MINUTES = 12
HARD_CUTOFF_MINUTES = 2
DISCOVERY_RETRY_SECONDS = 10
FORCED_EXIT_RETRY_SECONDS = 10

# Inventory
MAX_CONTRACTS_PER_ASSET = 50
INVENTORY_TIMEOUT_SECONDS = 300
RISK_BUDGET_PCT = 0.10  # 10% of balance, compounds as balance grows

# Risk
MAX_DAILY_LOSS_CENTS = 2000
MAX_WINDOW_LOSS_CENTS = 1000
VOLATILITY_SPIKE_PCT = 0.005
MAX_EXIT_LOSS_CENTS = 5

# Re-quote
REQUOTE_DRIFT_CENTS = 1

# States
IDLE = "IDLE"
DISCOVERING = "DISCOVERING"
QUOTING_BID = "QUOTING_BID"
QUOTING_ASK = "QUOTING_ASK"
EXITING = "EXITING"
DARK = "DARK"
